language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t swarsa/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true swarsa/react-test npm run test -- --coverage

after_success:
    - docker build -t swarsa/multi-client ./client
    - docker build -t swarsa/multi-nginx ./nginx
    - docker build -t swarsa/multi-server ./server
    - docker build -t swarsa/multi-worker ./worker
    # login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push them to docker hub
    - docker push swarsa/multi-client
    - docker push swarsa/multi-nginx
    - docker push swarsa/multi-server
    - docker push swarsa/multi-worker
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-660892587531"
    bucket_path: "docker-multi"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY